services:

  localstack:
    container_name: localstack
    image: localstack/localstack
    restart: always
    ports:
      - "4566:4566"
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-services.sh:/etc/localstack/init/ready.d/init-services.sh"