server:
  port: 8080
spring:
  application:
    name: hospital

resilience4j:
  circuitbreaker:
    instances:
      addressGateway:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true

logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG
    io.github.resilience4j: DEBUG