package br.com.hospital.core.exception

enum class Error(
    code: String,
    message: String
) {
    EMPLOYEE_NOT_FOUND_EXCEPTION("EMPLOYEE_NOT_FOUND_EXCEPTION", "EMPLOYEE_NOT_FOUND_EXCEPTION"),
    PATIENT_NOT_FOUND_EXCEPTION("PATIENT_NOT_FOUND_EXCEPTION", "PATIENT_NOT_FOUND_EXCEPTION"),
    ADDRESS_NOT_FOUND_EXCEPTION("ADDRESS_NOT_FOUND_EXCEPTION", "ADDRESS_NOT_FOUND_EXCEPTION")
}